[tool.black]
line-length = 100
target-version = ["py310"]

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["app"]

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
warn_return_any = true
warn_unused_configs = true
namespace_packages = true
mypy_path = "."

[[tool.mypy.overrides]]
module = "app.*"
disallow_untyped_defs = false
warn_unused_ignores = true
